# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-cloudwatch-logs
  description: This component is responsible for creation of CloudWatch Log Streams and Log Groups
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







